### ISSUE TITLE
the principle behind computing posterior probability and the estimate_probabilities

### ISSUE THREAD

**Issue by wmv2017** [Matt52/bayesian-testing#28]
Hi，first i like your code! Thanks a lot!
I want to know the principles about gamma_posteriors/dirichlet_posteriors/normal_posteriors/lognormal_posteriors
I found something about gamma_posteriors in VWO_SmartStats_technical_whitepaper, but it looks different. (I cant understand the 
1 / (b_priors_gamma[i] + totals[i])  in gamma_posteriors)
Is there any recommended material or website that i can learn about the different posteriors and the estimate_probabilities function?
Thanks a lot!

**Comment by Matt52** [comment]
Hi @wmv2017 thanks for you message!
You can check posteriors for instance on wikipedia: https://en.wikipedia.org/wiki/Conjugate_prior
Also, this Coursera course could be a good starting point: https://www.coursera.org/learn/bayesian-statistics

`1 / (totals[i] + b_priors_gamma[i])` in `gamma_posteriors_all` method is a scale of gamma distribution (used as a prior in Poisson test).
