### ISSUE TITLE
Which test is better for zero and negative values?

### ISSUE THREAD

**Issue by dailydreamer0** [Matt52/bayesian-testing#29]
From the first look Normal test will not work. Will Delta Normal test work with negative and zero values?

**Comment by Matt52** [comment]
I am not sure I understand but Normal test will work for Normal data (can be positive, 0 or negative).
Delta normal test is special case where your data contains some part of normally distributed data plus many zeros. Like a combination where you have some zeros (e.g. non conversions) and some normally distributed data.
