### ISSUE TITLE
'Totals' meaning in DeltaNormalDataTest

### ISSUE THREAD

**Issue by dailydreamer0** [Matt52/bayesian-testing#30]
Test example: there 3 users, only one user purchased something (twice). Nobody else purchased anything.

What should be the value of 'totals'?
- the number of ALL participants of the test. totals = 3.
- the number of participants who generated at least something. totals = 1
- the number of purchases made. totals=2

**Comment by Matt52** [comment]
`Totals is for total number of experiment observations (e.g. number of user sessions).
I am not sure how do you define 1 observation in your example. Is it 1 visit of a user? In such a case, you would have 3 visits. But this depends on how you want to define your experiment.
